/* 
	Josie Nordrum
	March 4, 2019

	Each new term in the Fibonacci sequence is 
	generated by adding the previous two terms. 
	By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence 
	whose values do not exceed four million, 
	find the sum of the even-valued terms.

	https://projecteuler.net/problem=2
*/

/*
	Solution:
		Every 3rd number is even
		Even fib numbers follow the pattern:
			x[n+1]= 4*x[n]+x[n-1]

*/

#include <stdio.h>
#include<math.h>

int main(void){
		
	int maxval = 4000000; 	

	int a0 = 1;
	int a1 = 2;
	int a2 = 0;
	int sum=0;

	while(a2 < maxval){
		// add to sum
		printf("adding %d\n", a2);
		sum += a2;

		// update values
		a0 = a1;
		a1 = a2;
		a2 = 4*a1+a0;
	}

	printf("Sum of even Fib numbser under %d is %d\n", maxval, sum);
	

	return 0;
}